INSERT INTO `ck1-jitpms`.`bas_code_config` (`id`, `app_id`, `code`, `sequence_name`, `i18n_id`, `prefix`, `length`, `min_value`, `max_value`, `increment_by`, `cycle_flag`, `order_flag`, `last_number`, `status`, `biz_type`, `suffix`, `time_stamp`, `is_time_stamp`, `patter`, `last_patter`) VALUES ('return_express_no', 'ck1', 'RETURN_EXPRESS_NO', '预报单号', NULL, 'YBD', 6, 1, 999999, 1, NULL, NULL, 1, 1, NULL, NULL, NULL, 1, 'yyyyMMdd', '20210331');

CREATE TABLE `return_express_detail` (
     `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
     `create_by` varchar(30) CHARACTER SET utf8 DEFAULT NULL COMMENT '创建人',
     `create_by_name` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '创建人名称',
     `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
     `update_by` varchar(30) CHARACTER SET utf8 DEFAULT NULL COMMENT '修改人',
     `update_by_name` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '修改人名称',
     `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
     `del_flag` int(2) NOT NULL DEFAULT '0' COMMENT '逻辑删除标识；2-已删除，0-未删除',
     `version` decimal(10,0) DEFAULT '1' COMMENT '版本号',
     `remark` varchar(2000) CHARACTER SET utf8 DEFAULT NULL COMMENT '备注',
     `seller_code` varchar(100) DEFAULT NULL COMMENT '客户代码',
     `from_order_no` varchar(60) DEFAULT NULL COMMENT '退件原始单号 原出库单号',
     `scan_code` varchar(255) DEFAULT NULL COMMENT '退件可扫描编码',
     `expected_no` varchar(60) DEFAULT NULL COMMENT '预报单号',
     `return_no` varchar(60) DEFAULT NULL COMMENT 'VMS处理单号',
     `process_type` varchar(50) DEFAULT NULL COMMENT '申请处理方式',
     `process_type_str` varchar(50) DEFAULT NULL COMMENT '申请处理方式str',
     `return_type` varchar(20) DEFAULT NULL COMMENT '退件类型[ 自有库存退件 转运单退件 外部渠道退件]',
     `return_type_str` varchar(20) DEFAULT NULL COMMENT '退件类型str[ 自有库存退件 转运单退件 外部渠道退件]',
     `return_channel` varchar(255) DEFAULT NULL COMMENT '退货渠道',
     `warehouse_code` varchar(50) DEFAULT NULL COMMENT '退件目标仓库编码',
     `warehouse_code_str` varchar(50) DEFAULT NULL COMMENT '退件目标仓库Str',
     `apply_process_method` varchar(50) DEFAULT NULL COMMENT 'VMS仓库使用处理方式',
     `apply_process_method_str` varchar(50) DEFAULT NULL COMMENT 'VMS仓库使用处理方式Str',
     `arrival_time` datetime DEFAULT NULL COMMENT '到仓时间',
     `finish_time` datetime DEFAULT NULL COMMENT '完成时间',
     `overdue` varchar(255) DEFAULT '0' COMMENT '是否逾期',
     `process_remark` varchar(500) DEFAULT NULL COMMENT '处理备注',
     `return_source` varchar(50) DEFAULT '1' COMMENT '退件单来源[申请退件，vms退件]',
     `return_source_str` varchar(50) DEFAULT '1' COMMENT '退件单来源Str[申请退件，vms退件]',
     `deal_status` varchar(255) DEFAULT NULL COMMENT '处理状态编码',
     `deal_status_str` varchar(255) DEFAULT NULL COMMENT '处理状态编码Str',
     PRIMARY KEY (`id`) USING BTREE,
     UNIQUE KEY `uni_expected_no` (`expected_no`),
     UNIQUE KEY `uni_return_no` (`return_no`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='return_express - 退货单详情表';

CREATE TABLE `return_express_good` (
       `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
       `create_by` varchar(30) CHARACTER SET utf8 DEFAULT NULL COMMENT '创建人',
       `create_by_name` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '创建人名称',
       `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
       `update_by` varchar(30) CHARACTER SET utf8 DEFAULT NULL COMMENT '修改人',
       `update_by_name` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '修改人名称',
       `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
       `version` decimal(10,0) DEFAULT '1' COMMENT '版本号',
       `association_id` int(11) NOT NULL COMMENT '关联退货单主键id',
       `remark` varchar(2000) CHARACTER SET utf8 DEFAULT NULL COMMENT '备注 仓库',
       `sku` varchar(255) NOT NULL COMMENT 'SKU',
       `sku_number` int(11) NOT NULL COMMENT 'SKU到库数量',
       `warehouse_qty` int(11) DEFAULT NULL COMMENT '仓库实际上架数量',
       `putaway_qty` int(11) DEFAULT NULL COMMENT '上架数量',
       `putaway_sku` varchar(255) DEFAULT NULL COMMENT '新上架编码',
       `process_remark` varchar(255) DEFAULT NULL COMMENT 'SKU处理备注',
       `del_flag` int(2) NOT NULL DEFAULT '0' COMMENT '逻辑删除标识；2-已删除，0-未删除',
       PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='return_express - 退货单sku详情表';

