INSERT INTO `ck1-jitpms`.`bas_code_config` (`id`, `app_id`, `code`, `sequence_name`, `i18n_id`, `prefix`, `length`, `min_value`, `max_value`, `increment_by`, `cycle_flag`, `order_flag`, `last_number`, `status`, `biz_type`, `suffix`, `time_stamp`, `is_time_stamp`, `patter`, `last_patter`) VALUES ('package_no', 'ck1', 'PACKAGE_NO', '揽件单号', NULL, NULL, 13, 1, 999999, 1, NULL, NULL, 1, 1, NULL, NULL, NULL, 1, 'yyyyMMdd', '20210401');

CREATE TABLE `package_management` (
      `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
      `create_by` varchar(30) CHARACTER SET utf8 DEFAULT NULL COMMENT '创建人',
      `create_by_name` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '创建人名称',
      `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
      `update_by` varchar(30) CHARACTER SET utf8 DEFAULT NULL COMMENT '修改人',
      `update_by_name` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '修改人名称',
      `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
      `version` decimal(10,0) DEFAULT '1' COMMENT '版本号',
      `remark` varchar(2000) CHARACTER SET utf8 DEFAULT NULL COMMENT '备注',
      `del_flag` int(2) NOT NULL DEFAULT '0' COMMENT '逻辑删除标识；2-已删除，0-未删除',
      `order_no` varchar(50) NOT NULL COMMENT '订单号',
      `seller_code` varchar(60) NOT NULL COMMENT '用户code',
      `link_user_name` varchar(50) NOT NULL COMMENT '联系人姓名',
      `link_phone` varchar(30) NOT NULL COMMENT '联系电话',
      `country_name_zh` varchar(100) NOT NULL DEFAULT '中国' COMMENT '国家 - 名称',
      `country_code` varchar(30) NOT NULL DEFAULT 'CN' COMMENT '国家 - 简码',
      `country_name_en` varchar(100) NOT NULL DEFAULT 'China' COMMENT '国家 - 英文名',
      `province_name_zh` varchar(100) NOT NULL COMMENT '省 - 名称',
      `province_code` varchar(30) DEFAULT NULL COMMENT '省 - 简码',
      `province_name_en` varchar(100) DEFAULT NULL COMMENT '省 - 英文名',
      `city_name_zh` varchar(100) NOT NULL COMMENT '市 - 名称',
      `city_code` varchar(30) DEFAULT NULL COMMENT '市 - 简码',
      `city_name_en` varchar(100) DEFAULT NULL COMMENT '市 - 英文名',
      `district_name_zh` varchar(100) NOT NULL COMMENT '区 - 名称',
      `district_code` varchar(30) DEFAULT NULL COMMENT '区 - 简码',
      `district_name_en` varchar(100) DEFAULT NULL COMMENT '区 - 英文名',
      `address_zh` varchar(255) DEFAULT NULL COMMENT '具体地址 - 中文名',
      `delivery_address` varchar(255) NOT NULL COMMENT '实际揽收地址',
      `address_en` varchar(255) DEFAULT NULL COMMENT '具体地址 - 英文名',
      `submit_time` datetime NOT NULL COMMENT '提交时间',
      `export_type` int(2) NOT NULL DEFAULT '0' COMMENT '是否导出【 0：未导出，1：已导出】',
      `export_time` datetime DEFAULT NULL COMMENT '导出时间',
      `delivery_time` datetime DEFAULT NULL COMMENT '实际揽件时间',
      `expected_delivery_time` date DEFAULT NULL COMMENT '期望收货日期',
      `receive_package_num` int(11) DEFAULT NULL COMMENT '实际揽收数量',
      `driver_name` varchar(50) DEFAULT NULL COMMENT '司机姓名',
      `driver_phone` varchar(50) DEFAULT NULL COMMENT '司机号码',
      `package_num` int(20) DEFAULT NULL COMMENT '揽件数量',
      `operation_type` int(2) NOT NULL DEFAULT '0' COMMENT '货物类型【 0：入库，1：转运】',
      PRIMARY KEY (`id`) USING BTREE,
      KEY `idx_seller_code` (`seller_code`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='package - 交货管理 - 揽件信息表';

CREATE TABLE `package_address` (
       `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
       `create_by` varchar(30) CHARACTER SET utf8 DEFAULT NULL COMMENT '创建人',
       `create_by_name` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '创建人名称',
       `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
       `update_by` varchar(30) CHARACTER SET utf8 DEFAULT NULL COMMENT '修改人',
       `update_by_name` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '修改人名称',
       `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
       `version` decimal(10,0) DEFAULT '1' COMMENT '版本号',
       `remark` varchar(2000) CHARACTER SET utf8 DEFAULT NULL COMMENT '备注',
       `del_flag` int(2) NOT NULL DEFAULT '0' COMMENT '逻辑删除标识；2-已删除，0-未删除',
       `seller_code` varchar(60) NOT NULL COMMENT '用户code',
       `default_flag` int(2) NOT NULL DEFAULT '0' COMMENT '是否未默认地址：0：非默认。1：默认',
       `link_user_name` varchar(50) NOT NULL COMMENT '联系人姓名',
       `link_phone` varchar(30) NOT NULL COMMENT '联系电话',
       `country_name_zh` varchar(100) NOT NULL DEFAULT '中国' COMMENT '国家 - 名称',
       `country_code` varchar(30) NOT NULL DEFAULT 'CN' COMMENT '国家 - 简码',
       `country_name_en` varchar(100) NOT NULL DEFAULT 'China' COMMENT '国家 - 英文名',
       `province_name_zh` varchar(100) NOT NULL COMMENT '省 - 名称',
       `province_code` varchar(30) DEFAULT NULL COMMENT '省 - 简码',
       `province_name_en` varchar(100) DEFAULT NULL COMMENT '省 - 英文名',
       `city_name_zh` varchar(100) NOT NULL COMMENT '市 - 名称',
       `city_code` varchar(30) DEFAULT NULL COMMENT '市 - 简码',
       `city_name_en` varchar(100) DEFAULT NULL COMMENT '市 - 英文名',
       `district_name_zh` varchar(100) NOT NULL COMMENT '区 - 名称',
       `district_code` varchar(30) DEFAULT NULL COMMENT '区 - 简码',
       `district_name_en` varchar(100) DEFAULT NULL COMMENT '区 - 英文名',
       `address_zh` varchar(255) DEFAULT NULL COMMENT '具体地址 - 中文名',
       `address_en` varchar(255) DEFAULT NULL COMMENT '具体地址 - 英文名',
       PRIMARY KEY (`id`) USING BTREE,
       KEY `idx_seller_code` (`seller_code`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='package - 交货管理 - 地址信息表';